import logging
import warnings
from typing import Any, List, Dict

import sglang.srt.entrypoints.openai.protocol
from sglang.srt.entrypoints.openai.protocol import ChatCompletionRequest, ChatCompletionResponse
from sglang.srt.entrypoints.openai.serving_chat import OpenAIServingChat
from sglang.srt.managers.io_struct import GenerateReqInput
from fastapi import Request

__all__ = [
    "instrument_sglang",
    "uninstrument_sglang",
]

logger = logging.getLogger(__name__)

class ChatCompletionResponsePatched(ChatCompletionResponse):
    prompt_token_ids: List[int] | None = None
    response_token_ids: List[List[int]] | None = None
    response_log_probs: List[List[float]] | None = None

original_build_chat_response = OpenAIServingChat._build_chat_response
original_handle_non_streaming_request = OpenAIServingChat._handle_non_streaming_request

# async def build_chat_response(
#     self: Any,
#     request: ChatCompletionRequest,
#     ret: List[Dict[str, Any]],
#     created: int,
# ) -> Any:
#     prompt_token_ids: List[int] | None = None
#     response_token_ids: List[List[int]] | None = None

#     async def _generate_inceptor():
#         nonlocal prompt_token_ids, response_token_ids
#         ret
#         # async for res in result_generator:
#         #     print("res:", res)
#         #     yield res
#         #     prompt_token_ids = res.prompt_token_ids
#         #     response_token_ids = [output.token_ids for output in res.outputs]

#     response = await original_build_chat_response(
#         self,
#         request,
#         _generate_inceptor()
#         created,
#     )
#     response = response.model_copy(
#         update={
#             "prompt_token_ids": prompt_token_ids,
#             "response_token_ids": response_token_ids,
#         }
#     )

#     return response

async def handle_non_streaming_request(self,
        adapted_request: GenerateReqInput,
        request: ChatCompletionRequest,
        raw_request: Request):
    # prompt_token_ids: List[int] | None = []
    # logger.info(f"input_ids: {adapted_request.input_ids}")

    response = await original_handle_non_streaming_request(
        self,
        adapted_request,
        request,
        raw_request
    )
    # logger.info(adapted_request.input_ids)
    # response = ChatCompletionResponsePatched(**response.model_dump())
    response.prompt_token_ids = adapted_request.input_ids
    return response

def build_chat_response(
    self: Any,
    request: ChatCompletionRequest,
    ret: List[Dict[str, Any]],
    created: int,
) -> Any:
    # prompt_token_ids: List[int] | None = None
    response_token_ids: List[List[int]] | None = []
    response_log_probs: List[List[float]] | None = []
    # logger.info(f"instructment ret: {ret[0].keys()}")
    def _generate_inceptor():
        nonlocal response_token_ids #prompt_token_ids
        for idx, ret_item in enumerate(ret):
            # logger.info(f"input_token_logprobs: {ret_item['meta_info']['input_token_logprobs']}")
            # logger.info(f"output_token_logprobs: {ret_item['meta_info']['output_token_logprobs']}")
            # cur_response_token_ids = [item[1] for item in ret_item["meta_info"]["output_token_logprobs"]]
            # cur_log_probs = [item[0] for item in ret_item["meta_info"]["output_token_logprobs"]]
            response_token_ids.append([item[1] for item in ret_item["meta_info"]["output_token_logprobs"]])
            response_log_probs.append([item[0] for item in ret_item["meta_info"]["output_token_logprobs"]])
        return ret
        # async for res in result_generator:
        #     print("res:", res)
        #     yield res
        #     prompt_token_ids = res.prompt_token_ids
        #     response_token_ids = [output.token_ids for output in res.outputs]

    response = original_build_chat_response(
        self,
        request,
        _generate_inceptor(),
        created,
    )
    # logger.info(f"response_token_ids: {response_token_ids}")    
    # response = response.model_copy(
    #     update={
    #         # "prompt_token_ids": prompt_token_ids,
    #         "response_token_ids": response_token_ids,
    #     }
    # )
    response = ChatCompletionResponsePatched(**response.model_dump())
    response.response_token_ids = response_token_ids
    response.response_log_probs = response_log_probs
    # logger.info(f"response: {type(response)} {response}")
    return response

def instrument_sglang():
    """Instrument vLLM to capture token IDs generated by engine.

    This instrumentation has been merged to upstream vLLM since v0.10.2.
    """
    if sglang.srt.entrypoints.openai.protocol.ChatCompletionResponse is ChatCompletionResponsePatched:
        warnings.warn("sglang is already instrumented. Skip the instrumentation.")
        return

    sglang.srt.entrypoints.openai.protocol.ChatCompletionResponse = ChatCompletionResponsePatched
    OpenAIServingChat._build_chat_response = build_chat_response
    OpenAIServingChat._handle_non_streaming_request = handle_non_streaming_request
    logger.info("enable instrument_sglang")


def uninstrument_sglang():
    """Uninstrument vLLM to stop capturing token IDs generated by engine."""
    OpenAIServingChat._build_chat_response = original_build_chat_response
    OpenAIServingChat._handle_non_streaming_request = original_handle_non_streaming_request
